config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end 

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def edit   
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article."
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def index 
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show 
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user &&  user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show 
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id 
      flash[:notice] = "Wellcome to the Alpha Blog #{@user.username}, you have successfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted."
    redirect_to articles_path
  end

  private 
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end 

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account."
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-full drop-shadow-xl")
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
  <div class="container mx-auto my-4 w-2/4 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="p-5">
      <p class="mb-2 text-2xl font-bold tracking-tight text-indigo-700 dark:text-white hover:underline hover:text-indigo-400">
        <%= link_to article.title, article_path(article) %>
      </p>
      <p class="mb-3 font-normal text-indigo-700 truncate">
        <%= article.description %>
      </p>
      <p class="mb-3 font-bold  text-sm text-center italic text-indigo-700 hover:underline hover:text-indigo-400">
        By <%= link_to article.user.username, user_path(article.user) %>
      </p>

      <p class="flex justify-center text-base">
      <% if article.categories.any? %>
        <div class=""><%= render article.categories %></div>
      <% end %>
      </p>

      <p class="mb-3 font-normal text-sm text-center italic text-indigo-700">Created <%= time_ago_in_words(article.created_at) %> ago,
        edited <%= time_ago_in_words(article.updated_at) %> ago
      </p>

      <div class="flex justify-center mt-8">
        <button type="button" class="py-2.5 px-5 mr-2 mb-2 text-sm font-medium focus:outline-none rounded-lg text-indigo-700 hover:bg-indigo-300 border border-gray-200 hover:text-white focus:z-10 focus:ring-4 focus:ring-gray-200"><%= link_to 'Show', article_path(article) %>
        </button>
        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
          <button type="button" class="py-2.5 px-5 mr-2 mb-2 text-sm font-medium focus:outline-none rounded-lg text-indigo-700 hover:bg-indigo-300 border border-gray-200 hover:text-white focus:z-10 focus:ring-4 focus:ring-gray-200"><%= link_to 'Edit', edit_article_path(article) %>
          </button>

          <button type="button" class="py-2.5 px-5 mr-2 mb-2 text-sm font-medium focus:outline-none rounded-lg text-indigo-700 hover:bg-indigo-300 border border-gray-200 hover:text-white focus:z-10 focus:ring-4 focus:ring-gray-200"><%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </button>
        <% end %>
      </div>  
    </div>
  </div>
<% end %>

app/views/articles/_footer.html.erb
<footer class="bg-violet-50 rounded-lg m-4">
  <div class="w-full mx-auto container md:p-6 p-4 md:flex md:items-center md:justify-between">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
      <li>
        <a href="https://github.com/lakysme" target="_blank" class="mr-4 hover:underline md:mr-6 ">Other projects</a>
      </li>
    </ul>
  </div>
</footer>

app/views/articles/_form.html.erb
<div class="container justify-center mx-auto m-10 text-m text-left text-gray-500 dark:text-gray-400">
  <%= render 'shared/errors', obj: @article %>
  <%= form_with(model: @article, local: true) do |f| %>
    <div class="p-5">
      <p class="text-indigo-800 text-xl text-center">
        <%= f.label :title %>
      </p>
      <p class="block w-full p-2 text-indigo-800 border-none bg-violet-300/25 sm:text-xs">
        <%= f.text_field :title %>
      </p>
    </div>
    
    <div class="p-5 pb-10">
      <p class="text-indigo-800 text-xl text-center">
        <%= f.label :description %>
      </p>
      <p class="block w-full p-2 text-indigo-800 border-none bg-violet-300/25 sm:text-xs">
        <%= f.text_area :description %>
      </p>
    </div>

    <div class="p-5 pb-10">
      <p class="text-indigo-800 text-xl text-center">
        <%= f.label :category %>
      </p>
      <p class="text-indigo-800 text-xl text-center">
        <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Please select a category for your article. (can be empty)"}, { multiple: true, size:3, class: "text-indigo-800 text-xl text-center bg-violet-300/25 mx-auto" })  %>
      </p>
    </div>

    <div class="text-white bg-indigo-400 hover:bg-violet-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 p-10">
        <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/articles/edit.html.erb
<h1 class="flex justify-center text-3xl text-indigo-500 mt-9 font-mono">Edit article</h1>

<%= render 'form' %>

<div class="flex justify-center text-xl text-indigo-500 hover:text-indigo-500/50 font-mono my-10 mb-64">
    <%= link_to 'Cancel and return to articles listing', articles_path %>
</div>

<%= render 'footer' %>

app/views/articles/index.html.erb
<h1 class="flex justify-center mb-10 text-3xl text-indigo-700 mt-9 font-mono">Articles listing page</h1>

<div class="flex justify-center tracking-widest text-indigo-700  font-mono text-xl">
  <%= will_paginate @articles, :container => false %>
</div>
  <%= render 'article' %>
<div class="flex justify-center tracking-widest text-indigo-700  font-mono text-xl">
  <%= will_paginate @articles, :container => false %>
</div>

<p class="flex justify-center text-xl font-mono my-10 text-indigo-500 hover:text-indigo-500/50">
  <%= link_to 'Create new article', new_article_path %>
</p>

<%= render 'footer' %>

app/views/articles/new.html.erb
<h1 class="flex justify-center text-3xl mt-9 text-indigo-500 font-mono">Create a new article</h1>
<div class="w-full">
    
    <%= render 'form' %>
    
    <div class="flex justify-center font-mono text-indigo-500 hover:text-indigo-500/50 text-xl my-10 mb-64"><%= link_to 'Return to articles listing', articles_path %></div>
    
</div>

<%= render 'footer' %>

app/views/articles/show.html.erb
<h1 class="flex justify-center text-indigo-500 text-3xl mt-9 font-mono">Showing article details</h1>

<div class="container justify-center mx-auto m-2 mt-5 p-6 py-10 h-auto rounded-lg space-y-4 text-m text-left text-indigo-700 text-lg bg-violet-200/50">
  <div>
    <p class="flex justify-center text-base mb-3">By <%= @article.user.username %></p>
    <p class="flex justify-center mb-2"><%= link_to gravatar_for(@article.user), user_path(@article.user) %>
    </p>
    <div class="flex justify-center text-base">
      <% if @article.categories.any? %>
        <div><%= render @article.categories %></div>
      <% end %>
    </div>
  </div>
  <p class="basis-1/3"><strong>Title: </strong><%= @article.title %></p>
  <p class="basis-1/3"><strong>Description: </strong><%= @article.description %></p>
</div>

  <div class="flex space-x-4 justify-center text-indigo-500 text-xl font-mono my-10 mb-72">
    <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
      <p class="hover:text-indigo-500/50 "><%= link_to 'Edit', edit_article_path(@article) %></p>
      <p> | </p>
      <p class="hover:text-indigo-500/50 "><%= link_to 'Delete', article_path(@article),  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></p>
      <p> | </p>
    <% end %>
    <p class="hover:text-indigo-500/50 "><%= link_to 'Return to articles listing', articles_path %></p>
  </div>

<%= render 'footer' %>

app/views/categories/_category.erb
<div class="rounded-full bg-black flex justify-center text-indigo-500 text-base">
  <button class=" inline-flex items-center justify-center px-2 py-1 text-sm font-bold uppercase leading-none hover:underline">
    <%= link_to category.name, category_path(category) %>
  </button>
</div>

app/views/categories/_form.html.erb
<div class="container justify-center mx-auto">
      <%= render 'shared/errors', obj: @category %>

      <%= form_with(model: @category, local: true) do |f| %>
        <div class="mb-6">
          <p class="block mb-2 text-xl font-medium text-indigo-600 dark:text-white">
            <%= f.label :name, "Category name" %>
          </p>
          <p class="bg-gray-50 border border-gray-300 text-indigo-500 text-sm rounded-lg focus:ring-violet-300 focus:border-violet-300 block w-full p-2.5" placeholder="Enter a name">
            <%= f.text_field :name %>
          </p>
        </div>

        <div class="text-white text-base bg-indigo-400 hover:bg-violet-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg w-full sm:w-auto px-5 py-2.5 text-center p-10">
          <%= f.submit %>
        </div>
      <% end %>
    </div>

app/views/categories/edit.html.erb
<h1 class="flex justify-center text-3xl mt-9 text-indigo-500 font-mono">Edit category name</h1>
<div class="w-full">  
    <%= render 'form' %>
    <div class="flex justify-center font-mono text-indigo-500 hover:text-indigo-500/50 text-xl my-10 mb-44">
        <%= link_to 'Cancel and return to category page', category_path(@category) %>
    </div>  
</div>

<%= render 'articles/footer' %>

app/views/categories/index.html.erb
<h1 class="flex justify-center mb-10 text-3xl text-indigo-700 mt-9 font-mono">Categories</h1>

<div class="flex justify-center tracking-widest text-indigo-700  font-mono text-xl">
  <%= will_paginate @categories, :container => false %>
</div>

<% @categories.each do |category| %>
  <div class="container mx-auto my-4 w-1/3 bg-white border border-gray-200 rounded-lg shadow">
    <div class="p-5">
      <p class="text-center mb-2 text-2xl font-bold tracking-tight text-indigo-700 dark:text-white hover:underline hover:text-indigo-400">
        <%= link_to category.name, category_path(category) %>
        <p class="flex justify-center mb-3 font-normal text-indigo-700 truncate">
          <%= pluralize(category.articles.count, "article") %>
        </p>
      </p>

      <p class="mb-3 font-normal text-sm text-center italic text-indigo-700">Created <%= time_ago_in_words(category.created_at) %> ago,
        edited <%= time_ago_in_words(category.updated_at) %> ago
      </p>  
    </div>
  </div>
<% end %>

<div class="flex justify-center tracking-widest text-indigo-700  font-mono text-xl">
  <%= will_paginate @categories, :container => false %>
</div>

<%= render 'articles/footer' %>

app/views/categories/new.html.erb
<h1 class="flex justify-center text-3xl mt-9 text-indigo-500 font-mono">Create a new category</h1>
<div class="w-full">  
    <div class="container justify-center mx-auto">
      <%= render 'shared/errors', obj: @category %>

      <%= form_with(model: @category, local: true) do |f| %>
        <div class="mb-6">
          <p class="block mb-2 text-xl font-medium text-indigo-600 dark:text-white">
            <%= f.label :name, "Category name" %>
          </p>
          <p class="bg-gray-50 border border-gray-300 text-indigo-500 text-sm rounded-lg focus:ring-violet-300 focus:border-violet-300 block w-full p-2.5" placeholder="Enter a name">
            <%= f.text_field :name %>
          </p>
        </div>

        <div class="text-white text-base bg-indigo-400 hover:bg-violet-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg w-full sm:w-auto px-5 py-2.5 text-center p-10">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
    <div class="flex justify-center font-mono text-indigo-500 hover:text-indigo-500/50 text-xl my-10 mb-44">
        <%= link_to 'Cancel and return to articles listing', articles_path %>
    </div>  
</div>

<%= render 'articles/footer' %>

app/views/categories/show.html.erb
<div class="container mx-auto relative">
  <h1 class="flex justify-center text-3xl my-9 text-indigo-500 font-mono">
    Category: <%= @category.name %>
  </h1>
</div>
<% if logged_in? && current_user.admin? %>
    <div class="p-5 flex place-content-center">
      <button type="button" class="flex justify-center py-2.5 px-5 mr-2 mb-2 text-sm font-medium rounded-lg text-indigo-700 hover:bg-indigo-300 border border-gray-200 hover:text-white">
        <%= link_to 'Edit category name', edit_category_path(@category) %>
      </button>
    </div>
<% end %>
  
  <h3 class="flex justify-center text-3xl my-5 text-indigo-500 font-mono">Articles</h3>

  <div class="apple_pagination flex justify-center tracking-widest text-indigo-700  font-mono text-xl">
    <%= will_paginate @articles, :container => false %>
  </div>
  
  <%= render 'articles/article' %>

  <div class="apple_pagination flex justify-center tracking-widest text-indigo-700  font-mono text-xl mb-2">
    <%= will_paginate @articles, :container => false %>
  </div>
  
  <div class="w-full">
    <div class="flex justify-center font-mono text-indigo-500 hover:text-indigo-500/50 text-xl mt-4">
      <%= link_to 'Return to articles listing', articles_path %>
    </div>
  </div>
  
<%= render 'articles/footer' %>

</div>

app/views/layouts/_navigation.html.erb
<nav class="relative flex flex-wrap items-center justify-between px-2 py-3 bg-indigo-400 mb-3 shadow-md m-0">
  <div class="container px-4 mx-auto flex flex-wrap items-center justify-between">
    <div class="w-full relative flex justify-between lg:w-auto  px-4 lg:static lg:block lg:justify-start">
      <a class="text-3xl font-bold leading-relaxed inline-block mr-4 py-2 whitespace-nowrap uppercase text-white" href="/">
        Alpha Blog
      </a>
    </div>
    <div class="lg:flex flex-grow items-center" id="example-navbar-warning">
      <ul class="flex flex-col lg:flex-row list-none ml-auto">
        <li class="nav-item">
          <a class="px-3 py-2 flex items-center text-base uppercase font-bold leading-snug text-white hover:opacity-75" href="/articles">
            Articles
          </a>
        </li>
        <li class="nav-item">
          <a class="px-3 py-2 flex items-center text-base uppercase font-bold leading-snug text-white hover:opacity-75" href="/categories">
            Categories
          </a>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <a class="px-3 py-2 flex items-center text-base uppercase font-bold leading-snug text-white hover:opacity-75" href="/articles/new">
              New article
            </a>
          </li>
        <% end %>
        <% if logged_in? && current_user.admin? %>
          <li class="nav-item">
            <a class="px-3 py-2 flex items-center text-base uppercase font-bold leading-snug text-white hover:opacity-75" href="/categories/new">
              New category
            </a>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="px-3 py-2 flex items-center text-base uppercase font-bold leading-snug text-white hover:opacity-75" href="/users">
             Bloggers
          </a>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <button type="button" class="px-3 py-2 flex items-center text-base uppercase font-bold leading-snug text-white hover:opacity-75">
            <%= "(Admin)-" if current_user.admin? %><%= link_to current_user.username, user_path(current_user) %>
            </button>
          </li>
          <li class="nav-item">
            <a class="px-3 py-2 flex items-center text-base uppercase font-bold leading-snug text-white hover:opacity-75" href="/logout">
              Log out
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="px-3 py-2 flex items-center text-base uppercase font-bold leading-snug text-white hover:opacity-75" href="/login">
              Log in
            </a>
          </li>
          <li class="nav-item">
            <a class="px-3 py-1 flex text-xl uppercase font-bold leading-snug text-white border rounded-full bg-indigo-700/25 hover:bg-indigo-600" href="/signup">
               Sign up!
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<div class="container mx-auto relative">
  <h1 class="flex justify-center text-3xl mt-9 mb-3 text-indigo-500 font-mono">Alpha Bloggers</h1>

  <div class="flex justify-center tracking-widest text-indigo-700  font-mono text-xl mt-2">
    <%= will_paginate @users, :container => false %>
  </div>

  <% @users.each do |user| %>
    <div class="container mx-auto my-4 w-2/4 bg-white border border-gray-200 rounded-lg shadow">

      <p class="font-normal text-xl text-center italic mt-3 text-indigo-700 hover:text-indigo-500">
        By <%= link_to user.username, user %>
      </p>

      <div class="p-5">
        <div class="flex justify-center">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-indigo-700 hover:underline hover:text-indigo-400">
            <%= link_to gravatar_for(user, size: 150), user %>
          </h5>
        </div>
      
        <p class="flex justify-center mb-3 font-normal text-indigo-700 truncate">
          <%= pluralize(user.articles.count, "article") %>
        </p>

        <p class="mb-3 font-normal text-sm text-center italic text-indigo-700">
          Joined <%= time_ago_in_words(user.created_at) %> ago
        </p>

        <div class="flex justify-center mt-8">
          <button type="button" class="py-2.5 px-5 mr-2 mb-2 text-sm font-medium focus:outline-none rounded-lg text-indigo-700 hover:bg-indigo-300 border border-gray-200 hover:text-white focus:z-10 focus:ring-4 focus:ring-gray-200 ">
            <%= link_to 'View profile', user %>
          </button>
          <% if logged_in? %>
            <% if user == current_user %>
              <button type="button" class="py-2.5 px-5 mr-2 mb-2 text-sm font-medium focus:outline-none rounded-lg text-indigo-700 hover:bg-indigo-300 border border-gray-200 hover:text-white focus:z-10 focus:ring-4 focus:ring-gray-200">
                <%= link_to 'Edit profile', edit_user_path(user) %>
              </button>
            <% end %>
            <% if current_user.admin? %>
              <button type="button" class="py-2.5 px-5 mr-2 mb-2 text-sm font-medium focus:outline-none rounded-lg text-indigo-700 focus:z-10 focus:ring-4 focus:ring-gray-200 hover:bg-red-200 border border-gray-200 hover:text-gray-700">
                <%= link_to 'Delete user', user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the user account and all associated articles?" } %>
              </button>
            <% end %>
          <% end %>

        </div>  
      </div>
    </div>
  <% end %>

  <div class="flex justify-center tracking-widest text-indigo-700  font-mono text-xl mb-2">
    <%= will_paginate @users, :container => false %>
  </div>
  
  <div class="w-full">
    <div class="flex justify-center font-mono text-indigo-500 hover:text-indigo-500/50 text-xl mt-4">
      <%= link_to 'Return to articles listing', articles_path %>
    </div>
  </div>

  <%= render 'articles/footer' %>

</div>

app/views/users/show.html.erb
<div class="container mx-auto relative">
  <h1 class="flex justify-center text-3xl my-9 text-indigo-500 font-mono">
    <%= @user.username %>'s profile
  </h1>
  
  <div class="flex mt-3 justify-center">
    <%= gravatar_for @user, size: 200 %>
  </div>

  <% if logged_in? && @user == current_user %>
    <div class="p-5 flex place-content-center">
      <button type="button" class="flex justify-center py-2.5 px-5 mr-2 mb-2 text-sm font-medium rounded-lg text-indigo-700 hover:bg-indigo-300 border border-gray-200 hover:text-white">
        <%= link_to 'Edit your profile', edit_user_path(@user) %>
      </button>
      <button type="button" class="flex justify-center py-2.5 px-5 mr-2 mb-2 text-sm font-medium rounded-lg text-indigo-700 hover:bg-red-200 border border-gray-200 hover:text-gray-700">
        <%= link_to 'Delete profile', user_path(current_user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </button>
    </div>
  <% end %>
  
  <h3 class="flex justify-center text-3xl my-5 text-indigo-500 font-mono">Articles</h3>

  <div class="apple_pagination flex justify-center tracking-widest text-indigo-700  font-mono text-xl">
    <%= will_paginate @articles, :container => false %>
  </div>
  
  <%= render 'articles/article' %>

  <div class="apple_pagination flex justify-center tracking-widest text-indigo-700  font-mono text-xl mb-2">
    <%= will_paginate @articles, :container => false %>
  </div>
  
  <div class="w-full">
    <div class="flex justify-center font-mono text-indigo-500 hover:text-indigo-500/50 text-xl mt-4">
      <%= link_to 'Return to articles listing', articles_path %>
    </div>
  </div>
  
<%= render 'articles/footer' %>

</div>